version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: inflow_postgres
    environment:
      POSTGRES_DB: inflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema_postgresql.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed_postgresql.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - inflow_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inflow_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inflow_backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: inflow_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      JWT_SECRET: your_super_secret_jwt_key_here_change_in_production
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000
      CORS_CREDENTIALS: true
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX: 100
      API_DOCS_ENABLED: true
      API_BASE_URL: http://localhost:3001
      LOG_LEVEL: info
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - inflow_network
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inflow_frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
      GENERATE_SOURCEMAP: false
      SKIP_PREFLIGHT_CHECK: true
      WDS_SOCKET_HOST: 0.0.0.0
      WDS_SOCKET_PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - inflow_network
    command: npm start

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: inflow_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - inflow_network
    profiles:
      - production

volumes:
  postgres_data:

networks:
  inflow_network:
    driver: bridge