version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inflow_backend
    env_file:
      - ./synology.env
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET:-change_me}
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3001}
      LOG_LEVEL: info
      API_DOCS_ENABLED: "true"
    ports:
      - "3002:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - inflow_network
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
    container_name: inflow_frontend
    environment:
      REACT_APP_API_URL: http://localhost:3002/api
      GENERATE_SOURCEMAP: "false"
      SKIP_PREFLIGHT_CHECK: "true"
      WDS_SOCKET_HOST: 0.0.0.0
      WDS_SOCKET_PORT: 3001
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - inflow_network
    command: npm start

networks:
  inflow_network:
    driver: bridge


